name: Publish Release

on:
  push:
    tags: ['v[0-9]+\.[0-9]+\.[0-9]+.*']


jobs:
  check-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Check if tag follows SemVer
        id: semver-check
        run: |
          echo "github.event.ref: ${{ github.event.ref }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"

  create-release:
    runs-on: ubuntu-latest
    needs: check-tag
    if: needs.check-tag.result == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Create Release
        id: create_release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.ref }}
          release_name: Release ${{ github.event.ref }}
          body: ${{ steps.release_notes.outputs.notes }}
          draft: false
          prerelease: false
